version: '3.4'

services:
  idp-service:
    image: ${DOCKER_REGISTRY-}idpruntime
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 1000:80 
     - 1001:443 
    networks: 
     - localhost_default

networks:
  localhost_default:
   external: true